version: "3"
virtualmachines:
- name: host
  image: projects/tmm-instruqt-11-26-2021/global/images/virt-rhel-2023-07-27
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-2
  nested_virtualization: true
secrets:
- name: ACTIVATION_KEY
- name: SSHKEY
