---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Installing Leapp
    - name: module-02
      label: Running the Pre-upgrade Assistant
    - name: module-03
      label: Fixing inhibited results
    - name: module-04
      label: Running the Upgrade
tabs:
  - name: ">_ root"
    port: 443
    path: /tty1
    user: root
    host: rhel
