== What is Leapp?

Red Hat’s leapp tool provides existing Red Hat Enterprise Linux 7 and 8
instances to an upgrade path from one major version to the next. This
can be done on a one-to-one basis or en mass with a tool like Satellite.
The Leapp tooling also includes a pre-upgrade assistant that makes it
easy to identify breaking changes or warn about potential issues before
any lasting changes are made to the system.

Before diving in, the question you have to ask is: is this workload
worth executing a rebuild from scratch? That process can be tedious and
time consuming. Doing an in-place upgrade retains the subscription,
installed packages, user data, and configurations all while saving the
time and resources required to deploy fresh.

== Installing Leapp

To get started, it is highly recommended that you update all packages on
your system to the latest version available. (Note: for this lab,
updates have already been run for you.)

Leapp is a supported operation for RHEL which means support tickets can
be opened in case obstacles are encountered. It also means that the
leapp utility is available straight from the Red Hat package repository.
First, verify the version of Red Hat Enterprise Linux that you have
installed:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat /etc/redhat-release
----

.Output
[source,text]
----
Red Hat Enterprise Linux release 7.9 (Maipo)
----

First, you need to enable specific rhel-7-server repositories. These have already been enabled for you in this lab environment, but we will use the subscription-manager command to enable them and verify they are active.

TIP: See how you can actually combine these two operations into one!

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms
----

.Output
[source,text]
----
Repository 'rhel-7-server-rpms' is enabled for this system.
Repository 'rhel-7-server-extras-rpms' is enabled for this system.
----

Next, use the DNF package manager to install leapp and its dependencies:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
yum install -y leapp-upgrade
----

.Output
[source,text]
----
<<< OUTPUT ABBRIDGED >>>

  Verifying  : libcomps-0.1.8-14.el7.x86_64      18/19
  Verifying  : leapp-deps-0.17.0-2.el7_9.noarch  19/19

Installed:
  leapp-upgrade-el7toel8.noarch 0:0.20.0-9.el7_9

<<< OUTPUT ABBRIDGED >>>
Complete!
----

Verify the install was successful:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
leapp --version
----

.Output
[source,text]
----
leapp version 0.17.0
----
